---
- hosts: lan_nodes
  become: true
  tasks:
    - name: install packages (1)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - vim
          - haveged
          - pip
          
    - name: fetch docker apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      
    - name: Refresh cache
      apt:
        update_cache: yes
        
    - name: Update distro
      apt:
        name: "*"
        state: latest
        
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        
    - name: install packages (2)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      tags:
        - install_docker

    - name: configure docker.json
      template:
        src: docker/daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644
      tags:
        - docker.json

    - name: install docker compose
      pip:
        name:
          - docker-compose
      tags:
        - install_compose

    - name: enable docker service
      service:
        name: docker
        enabled: yes
        
    - name: disable ntp service
      service:
        name: ntp
        enabled: no

